Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LojaRazor.Models
{
    public class Categoria
    {
        public string Nome { get; set; }

        public Categoria(string nome)
        {
            this.Nome = nome;
        }
    }
}

Models/Departamento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Departamento
    {
        public string Nome { get; set; }

        public IList<Categoria> Categorias { get; set; }

        public Departamento()
        {
            Categorias = new List<Categoria>();
        }
    }
}

Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Produto
    {
        
        public string Nome { get; set; }

        public string Descricao { get; set; }

        public decimal Preco { get; set; }

        public Produto(string nome, string descricao, decimal preco)
        {
            this.Nome = nome;
            this.Descricao = descricao;
            this.Preco = preco;
        }
    }
}

Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Usuario
    {
        [Required]
        public String Nome { get; set; }

        [Required, EmailAddress]
        public String Email { get; set; }

        [Required, MinLength(3)]
        public String Senha { get; set; }

        [Required]
        public DateTime DataDeNascimento { get; set; }

        [Required]
        public String Endereco { get; set; }

        public String Complemento { get; set; }

        [Required, RegularExpression("\\d{5}-\\d{3}")]
        public String CEP { get; set; }

        public string Observacoes { get; set; }

        public bool RecebePromocoes { get; set; }
    }
}

Controllers/AutenticacaoController.cs
using LojaRazor.DAO;
using LojaRazor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class AutenticacaoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Autentica(string email, string senha)
        {
            UsuariosDAO dao = new UsuariosDAO();
            Usuario usuarioLogado = dao.Busca(email, senha);
            if (usuarioLogado != null)
            {
                Session["usuarioLogado"] = usuarioLogado.Nome;
                return RedirectToAction("Index", "Home");
            }
            return View("Index");
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/HomeController.cs
using LojaRazor.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            DepartamentosDAO departamentosDAO = new DepartamentosDAO();
            ProdutosDAO produtosDAO = new ProdutosDAO();
            ViewBag.Departamentos = departamentosDAO.Lista();
            ViewBag.Produtos = produtosDAO.Ofertas();
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contato()
        {
            return View();
        }
    }
}

Controllers/UsuariosController.cs
using LojaRazor.DAO;
using LojaRazor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class UsuariosController : Controller
    {
        public ActionResult Form(string email)
        {
            Usuario u = new Usuario()
            {
                Email = email
            };
            return View(u);
        }

        public ActionResult Cadastra(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                UsuariosDAO dao = new UsuariosDAO();
                dao.Adiciona(usuario);
                Session["usuarioLogado"] = usuario.Nome;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("Form", usuario);
            }
        }

    }
}

Views/Autenticacao/Index.cshtml
<div class="hero-unit span6">
    
    <h2>Login</h2>

    <p>Já Possui Cadastro? Então faça seu login</p>
    <form action="@Url.Action("Autentica", "Autenticacao")">
        <input type="text" class="input-block-level" placeholder="E-mail" />

        <input type="password" class="input-block-level" placeholder="Senha" />

        <input type="submit" class="btn btn-large btn-primary" value="Fazer Login" />
    </form>
</div>

<div class="hero-unit span6">
    <h2>Novo Usuário?</h2>

    <p>Se você ainda não tem um cadastro, informe qual é o e-mail que você deseja associar com sua conta</p>

    <form action="@Url.Action("Form", "Usuarios")">
        <input type="text" class="input-block-level" placeholder="E-mail" name="Email"/>

        <input type="submit" class="btn btn-large btn-primary" value="Criar Conta" />
    </form>
</div>

Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
    <head>
        <link href="~/Content/bootstrap/css/bootstrap.css" rel="stylesheet"/>
        <link hreef="~/Content/style.css" rel="stylesheet" />
    </head>
    <body>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3">
                    <div class="sidebar-nav well">
                        <ul>
                            @foreach (var departamento in ViewBag.Departamentos)
                            {
                                <li class="nav-header">@departamento.Nome</li>
                                foreach (var categoria in departamento.Categoias)
                                {
                                    <li>@categoria.Nome</li>
                                }
                            }
                        </ul>
                    </div>
                </div>

                <div class="span9">

                </div>
            </div>
        </div>
    </body>
</html>

Views/Usuarios/Form.cshtml
<form action="@Url.Action("Cadastra")" method="post">
    <fieldset>
        <legend>Dados Pessoais</legend>

        <label for="nome">Nome: </label>
        <input id="nome" type="text" name="usuario.Nome" />

        <label for="email">E-mail: </label>
        <input id="email" type="text" name="usuario.Email" />

        <label for="senha">Senha:</label>
        <input id="senha" type="password" name="usuario.Senha" />

        <label for="dataDeNascimento">Data de Nascimento: </label>
        <input id="dataDeNascimento" type="text" name="usuario.DataDeNascimento" />
    </fieldset>

    <fieldset>
        <legend>Dados de Entrega</legend>

        <label for="endereco">Endereço: </label>
        <input id="endereco" type="text" name="usuario.Endereco" />

        <label for="complemento">Complemento: </label>
        <input id="complemento" type="text" name="usuario.Complemento" />

        <label for="cep">CEP: </label>
        <input id="cep" type="text" name="usuario.CEP" />

        <label for="observacoes">Observações: </label>
        <textarea id="observacoes" name="usuario.Observacoes"></textarea>
    </fieldset>
    <div>
        <input name="usuario.RecebePromocoes" type="checkbox" value="true" />
        Desejo receber informações sobre promoções
    </div>

    <input type="submit" value="Cadastrar" class="btn btn-large" />

</form>